#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.lab4.local
manage_etc_hosts: true

users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true

packages:
  - python3
  - python3-apt
  - qemu-guest-agent

runcmd:
  - systemctl enable --now qemu-guest-agent
