---
- name: Common setup (all hosts)
  hosts: all
  become: true
  roles:
    - common
    - users

- name: Configure MariaDB
  hosts: db
  become: true
  roles:
    - mariadb

- name: Configure web application and Nginx
  hosts: workers
  become: true
  roles:
    - webapp
    - nginx
